apiVersion: v1
kind: Service
metadata:
  name: usermgmt-service
  labels:
    app: usermgmt
spec:
  selector:
    app: usermgmt
  ports:
  - name: http
    protocol: TCP
    port: 3553
    targetPort: 5037
  type: LoadBalancer
